---
mapping_algorithm: 'BEST_FIT'
cores_number: 3
scheduling_algorithm: 'CGO'
scheduling_time_limit: 20
fitness_func: 'CUSTOM'

show_plots: Yes
save_plots: Yes
save_result: Yes

cgo_max_iterations: 100
cgo_population_size: 20
cgo_job_mutation_size: 5
cgo_order_mutation_size: 5

avo_max_iterations: 100
avo_population_size: 20